### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by sokNhokgit** [PNC-NODE-PROJECT/G06-NODE-PROJECT#1]

**Comment by sokNhokgit** [comment]
![image](https://user-images.githubusercontent.com/98095874/165306805-9a7c073c-e6f1-4e61-880e-79a712a3a8d9.png)

**Comment by VichetMorm** [comment]
![image_2022_04_26T13_23_28_643Z](https://user-images.githubusercontent.com/90229555/165309782-e43a9cb6-2333-4dd0-9b92-fbd4cf142b9b.png)
